### ISSUE TITLE
after install on windows it cannot open .

### ISSUE THREAD

**Issue by ericvlog** [alishanjack/h-box#1]
Traceback (most recent call last):
  File "main.py", line 4, in <module>
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 986, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 680, in _load_unlocked
  File "PyInstaller\loader\pyimod02_importers.py", line 352, in exec_module
  File "spider.py", line 13, in <module>
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 986, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 680, in _load_unlocked
  File "PyInstaller\loader\pyimod02_importers.py", line 352, in exec_module
  File "db.py", line 21, in <module>
sqlite3.OperationalError: unable to open database file

**Comment by alishanjack** [comment]
pelease download v2.0.5 version or clone source code。

**Comment by ferelking242** [comment]
i have the same problem 

Traceback (most recent call last):
  File "main.py", line 26, in <module>
  File "logging\__init__.py", line 2003, in basicConfig
  File "logging\__init__.py", line 1146, in __init__
  File "logging\__init__.py", line 1175, in _open
PermissionError: [Errno 13] Permission denied: 'C:\\Program Files (x86)\\h-box\\logfile.log'

**Comment by alishanjack** [comment]
Try not to install the software on the C drive ，There will be write permission issues。Try to install on D drive
