### ISSUE TITLE
h box error on win11

### ISSUE THREAD

**Issue by ferelking242** [alishanjack/h-box#2]
i get this error on windows 11

Traceback (most recent call last):
  File "main.py", line 26, in <module>
  File "logging\__init__.py", line 2003, in basicConfig
  File "logging\__init__.py", line 1146, in __init__
  File "logging\__init__.py", line 1175, in _open
PermissionError: [Errno 13] Permission denied: 'C:\\Program Files (x86)\\h-box\\logfile.log'

**Comment by alishanjack** [comment]
Try not to install the software on the C drive ，There will be write permission issues。Try to install on D drive
